baseURL = 'https://JohnsonSun10.github.io/'
languageCode = 'en-us'
title = 'Yu-Hung Johnson Sun'

theme = "love"

# Author config
# 作者配置
[author]
  name = "xxxx"
  email = ""
  link = ""

[menu]
  [[menu.main]]
    weight = 1
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = "" 
  [[menu.main]]
    weight = 2
    identifier = "research"
    # you can add extra information before the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "Research"
    url = "/research/"
    # title will be shown when you hover on this menu link
    # 当您将鼠标悬停在此菜单链接上时, 将显示标题
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "CV"
    pre = ""
    post = ""
    name = "CV"
    url = "/CV/"
    title = ""

[params]
  # site default theme ["auto", "light", "dark"]
  # 网站默认主题 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/dillonzq/LoveIt"
  # which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # date format
  # 日期格式
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  # 网站标题, 用于 Open Graph 和 Twitter Cards
  title = "LoveIt"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
  description = "Hugo theme - LoveIt"
  # website images for Open Graph and Twitter Cards
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]

  # Header config
  # 页面头部导航栏配置
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    # 页面头部导航栏标题配置
    [params.header.title]
      # URL of the LOGO
      # LOGO 的 URL
      logo = ""
      # title name
      # 标题名称
      name = "Yu-Hung Johnson Sun"
      post = ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit = false

  # Home page config
  # 主页信息设置
  [params.home]
    # amount of RSS pages
    # RSS 文章数目
    rss = 10
    # Home page profile
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.png"
      # title shown in home page (HTML format is supported)
      # 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "A Clean, Elegant but Advanced Hugo Theme"
      # whether to use typeit animation for subtitle
      # 是否为副标题显示打字机动画
      typeit = true
      # whether to show social links
      # 是否显示社交账号
      social = true
      # disclaimer (HTML format is supported)
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # Home page posts
    # 主页文章列表

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 2
        identifier = "research"
        pre = ""
        post = ""
        name = "Research"
        url = "/research/"
        title = ""
      [[languages.en.menu.main]]
        weight = 3
        identifier = "contact"
        pre = ""
        post = ""
        name = "Contact"
        url = "/contact/"
        title = ""
      [[languages.en.menu.main]]
        weight = 4
        identifier = "CV"
        pre = ""
        post = ""
        name = "CV"
        url = "https://drive.google.com/file/d/1oK9um19o07sgMXzabpbIr2rbu_G1CYP-/view?usp=sharing"
        title = ""
      [[languages.en.menu.main]]
        weight = 6
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/JohnsonSun10"
        title = "GitHub"
      [[languages.en.menu.main]]
        weight = 7
        identifier = "LinkedIn"
        pre = "<i class='fab fa-linkedin fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://www.linkedin.com/in/johnsonsunmoon/"
        title = "LinkedIn"
    [languages.en.params]
      [languages.en.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
        [languages.en.params.search.algolia]
          index = "index.en"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      [languages.en.params.home]
        rss = 10
        [languages.en.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.png"
          title = ""
          subtitle = "PhD Student | Political Science | National Taiwan University"
          typeit = true
          social = true
          disclaimer = ""
      [languages.en.params.social]
        GitHub = "JohnsonSun10"
        Email = "yuhungsun11@gmail.com"
        LinkedIn = "johnsonsunmoon"

  [languages.zh-tw]
    weight = 2
    languageCode = "zh-TW"
    languageName = "中文"
    hasCJKLanguage = true
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.zh-tw.menu]
      [[languages.zh-tw.menu.main]]
        weight = 2
        identifier = "posts"
        pre = ""
        post = ""
        name = "研究"
        url = "/research/"
        title = ""
      [[languages.zh-tw.menu.main]]
        weight = 3
        identifier = "tags"
        pre = ""
        post = ""
        name = "聯絡資訊"
        url = "/contact/"
        title = ""
      [[languages.zh-tw.menu.main]]
        weight = 4
        identifier = "CV"
        pre = ""
        post = ""
        name = "個人履歷"
        url = "https://drive.google.com/file/d/1Ky-_4Qb1qXQIS7C-yiYiDM1SWVhZCZk1/view?usp=sharing"
      [[languages.zh-tw.menu.main]]
        weight = 6
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/JohnsonSun10"
        title = "GitHub"
      [[languages.zh-tw.menu.main]]
        weight = 7
        identifier = "LinkedIn"
        pre = "<i class='fab fa-linkedin fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://www.linkedin.com/in/johnsonsunmoon/"
        title = "LinkedIn"
    [languages.zh-tw.params]
      [languages.zh-tw.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 50
        highlightTag = "em"
        absoluteURL = false
        [languages.zh-tw.params.search.algolia]
          index = "index.zh-tw"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      [languages.zh-tw.params.home]
        rss = 10
        [languages.zh-tw.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.png"
          title = ""
          subtitle = "國立臺灣大學 | 政治學研究所 | 博士生"
          typeit = true
          social = true
          disclaimer = ""
      [languages.zh-tw.params.social]
        GitHub = "JohnsonSun10"
        Email = "yuhungsun11@gmail.com"
        LinkedIn = "johnsonsunmoon"
      [languages.zh-tw.params.header.title]
        logo = ""
        name = "孫育弘"
        post = ""
        # whether to use typeit animation for title name
        # 是否为标题显示打字机动画
        typeit = false